.class public Landroid/ext/qm;
.super Ljava/io/Writer;
.source "src"


# instance fields
.field final a:Landroid/ext/Script$Consts;

.field private final b:Ljava/io/Writer;

.field private final c:Ljava/lang/String;


# direct methods
.method public constructor <init>(Ljava/lang/String;)V
    .registers 6

    .prologue
    .line 26
    invoke-direct {p0}, Ljava/io/Writer;-><init>()V

    .line 27
    new-instance v0, Ljava/io/File;

    invoke-direct {v0, p1}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 28
    invoke-virtual {v0}, Ljava/io/File;->getParentFile()Ljava/io/File;

    move-result-object v1

    .line 29
    if-eqz v1, :cond_0

    invoke-virtual {v1}, Ljava/io/File;->mkdirs()Z

    .line 30
    :cond_0
    iput-object p1, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    .line 31
    new-instance v1, Ljava/io/BufferedWriter;

    new-instance v2, Ljava/io/OutputStreamWriter;

    new-instance v3, Ljava/io/FileOutputStream;

    invoke-direct {v3, v0}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V

    invoke-direct {v2, v3}, Ljava/io/OutputStreamWriter;-><init>(Ljava/io/OutputStream;)V

    invoke-direct {v1, v2}, Ljava/io/BufferedWriter;-><init>(Ljava/io/Writer;)V

    iput-object v1, p0, Landroid/ext/qm;->b:Ljava/io/Writer;

    .line 32
    invoke-direct {p0}, Landroid/ext/qm;->c()V

    .line 34
    const/4 v0, 0x0

    invoke-static {v0}, Landroid/ext/Script;->a(Ljava/util/ArrayList;)Landroid/ext/Script$Consts;

    move-result-object v0

    iput-object v0, p0, Landroid/ext/qm;->a:Landroid/ext/Script$Consts;

    .line 35
    return-void
.end method

.method static synthetic a(Landroid/ext/qm;)Ljava/lang/String;
    .registers 2

    .prologue
    .line 22
    iget-object v0, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    return-object v0
.end method

.method private a(Ljava/lang/String;Ljava/lang/Throwable;)V
    .registers 5

    .prologue
    .line 68
    new-instance v0, Ljava/lang/StringBuilder;

    const-string v1, "Failed write text to record file: "

    invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    iget-object v1, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const/16 v1, 0xa

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0, p2}, Landroid/ext/la;->b(Ljava/lang/String;Ljava/lang/Throwable;)I

    .line 70
    invoke-virtual {p0}, Landroid/ext/qm;->a()V

    .line 71
    new-instance v0, Landroid/ext/qn;

    invoke-direct {v0, p0, p2}, Landroid/ext/qn;-><init>(Landroid/ext/qm;Ljava/lang/Throwable;)V

    invoke-static {v0}, Landroid/ext/rx;->a(Ljava/lang/Runnable;)V

    .line 84
    return-void
.end method

.method private c()V
    .registers 7

    .prologue
    const/4 v5, 0x1

    .line 87
    const-string v0, "-- Script generated by GameGuardian %gg_ver% (%gg_build%) at %now% for %t_name% [%t_pkg% %t_ver% (%t_build%)]\r\n-- Lua help: http://gameguardian.net/help/\r\n\r\n-- options\r\nlocal scriptName = [=====[Script for %t_name% %t_ver%]=====]\r\nlocal scriptVersion = \'1.0.0\'\r\nlocal scriptAuthor = \'User\'\r\nlocal startToast = \'\'\r\n-- 0 - no check; 1 - check package only, 2 - check package and build\r\nlocal checkTarget = 0\r\n\r\nlocal targetName = [=====[%t_name%]=====]\r\nlocal targetPkg = \'%t_pkg%\'\r\nlocal targetVersion = [=====[%t_ver%]=====]\r\nlocal targetBuild = %t_build%\r\n\r\n-- functions\r\n\r\n-- init\r\ngg.require(\'%gg_ver%\', %gg_build%)\r\n\r\nif startToast ~= \'\' then startToast = \'\\n\'..startToast end\r\ngg.toast(scriptName..\' v\'..scriptVersion..\' by \'..scriptAuthor..startToast)\r\n\r\nif checkTarget ~= 0 then\r\n\tlocal info = gg.getTargetInfo()\r\n\tlocal check = false\r\n\tlocal current = false\r\n\tif checkTarget >= 1 then\r\n\t\tcheck = targetPkg\r\n\t\tcurrent = info.packageName\r\n\tend\r\n\tif checkTarget >= 2 then\r\n\t\tcheck = check..\' \'..targetVersion..\' (\'..targetBuild..\')\'\r\n\t\tcurrent = current..\' \'..info.versionName..\' (\'..info.versionCode..\')\'\r\n\tend\r\n\tif check ~= current then\r\n\t\tgg.alert(\'This script for \"\'..targetName..\'\" [\'..check..\'].\\nYou select \"\'..info.label..\'\" [\'..current..\'].\\nNow script exit.\')\r\n\t\tos.exit()\r\n\tend\r\nend\r\nlocal revert = nil\r\n\r\n-- main code\r\n"

    .line 133
    const-string v1, "\r"

    const-string v2, ""

    invoke-virtual {v0, v1, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 135
    const-string v1, "%gg_ver%"

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const v3, 0x42e53333    # 114.6f

    int-to-float v4, v5

    mul-float/2addr v3, v4

    const/high16 v4, 0x41580000    # 13.5f

    sub-float/2addr v3, v4

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(F)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 136
    const-string v1, "%gg_build%"

    const v2, 0x467db666

    int-to-float v3, v5

    mul-float/2addr v2, v3

    const v3, 0x42bf3333    # 95.6f

    sub-float/2addr v2, v3

    const/high16 v3, 0x3f000000    # 0.5f

    add-float/2addr v2, v3

    float-to-int v2, v2

    invoke-static {v2}, Ljava/lang/Integer;->toString(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 137
    const-string v1, "%now%"

    new-instance v2, Ljava/text/SimpleDateFormat;

    const-string v3, "yyyy-MM-dd HH:mm:ss"

    sget-object v4, Ljava/util/Locale;->US:Ljava/util/Locale;

    invoke-direct {v2, v3, v4}, Ljava/text/SimpleDateFormat;-><init>(Ljava/lang/String;Ljava/util/Locale;)V

    new-instance v3, Ljava/util/Date;

    invoke-direct {v3}, Ljava/util/Date;-><init>()V

    invoke-virtual {v2, v3}, Ljava/text/SimpleDateFormat;->format(Ljava/util/Date;)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 139
    sget-object v1, Landroid/ext/MainService;->instance:Landroid/ext/MainService;

    iget-object v1, v1, Landroid/ext/MainService;->ap:Landroid/ext/qh;

    .line 140
    if-eqz v1, :cond_1

    .line 141
    iget-object v2, v1, Landroid/ext/qh;->c:Ljava/lang/String;

    .line 142
    const-string v1, "%t_pkg%"

    invoke-virtual {v0, v1, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 145
    const/4 v1, 0x0

    :try_start_0
    invoke-static {v2, v1}, Landroid/ext/Tools;->d(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;

    move-result-object v1

    .line 146
    if-eqz v1, :cond_1

    .line 147
    iget-object v3, v1, Landroid/content/pm/PackageInfo;->versionName:Ljava/lang/String;

    if-eqz v3, :cond_0

    const-string v3, "%t_ver%"

    iget-object v4, v1, Landroid/content/pm/PackageInfo;->versionName:Ljava/lang/String;

    invoke-virtual {v0, v3, v4}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 148
    :cond_0
    const-string v3, "%t_build%"

    iget v4, v1, Landroid/content/pm/PackageInfo;->versionCode:I

    invoke-static {v4}, Ljava/lang/Integer;->toString(I)Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v0, v3, v4}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v0

    .line 150
    iget-object v1, v1, Landroid/content/pm/PackageInfo;->applicationInfo:Landroid/content/pm/ApplicationInfo;

    .line 151
    if-eqz v1, :cond_1

    .line 152
    invoke-static {v1}, Landroid/ext/Tools;->a(Landroid/content/pm/ApplicationInfo;)Ljava/lang/String;

    move-result-object v1

    .line 153
    if-eqz v1, :cond_1

    .line 154
    const-string v3, "%t_name%"

    invoke-virtual {v0, v3, v1}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;
    :try_end_0
    .catch Landroid/content/pm/PackageManager$NameNotFoundException; {:try_start_0 .. :try_end_0} :catch_0

    move-result-object v0

    .line 163
    :cond_1
    :goto_0
    iget-object v1, p0, Landroid/ext/qm;->b:Ljava/io/Writer;

    invoke-virtual {v1, v0}, Ljava/io/Writer;->write(Ljava/lang/String;)V

    .line 164
    return-void

    .line 158
    :catch_0
    move-exception v1

    .line 159
    new-instance v3, Ljava/lang/StringBuilder;

    const-string v4, "Pkg not found: "

    invoke-direct {v3, v4}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v2, v1}, Landroid/ext/la;->b(Ljava/lang/String;Ljava/lang/Throwable;)I

    goto :goto_0
.end method


# virtual methods
.method public a()V
    .registers 4

    .prologue
    .line 54
    sget-object v0, Landroid/ext/MainService;->instance:Landroid/ext/MainService;

    invoke-virtual {v0, p0}, Landroid/ext/MainService;->a(Landroid/ext/qm;)V

    .line 56
    :try_start_0
    iget-object v0, p0, Landroid/ext/qm;->b:Ljava/io/Writer;

    invoke-virtual {v0}, Ljava/io/Writer;->close()V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0

    .line 60
    :goto_0
    new-instance v0, Ljava/lang/StringBuilder;

    const v1, 0x7f0702e6

    invoke-static {v1}, Landroid/ext/Tools;->c(I)Ljava/lang/String;

    move-result-object v1

    invoke-static {v1}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    const-string v1, ": "

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    iget-object v1, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Landroid/ext/Tools;->b(Ljava/lang/String;)V

    .line 61
    return-void

    .line 57
    :catch_0
    move-exception v0

    .line 58
    new-instance v1, Ljava/lang/StringBuilder;

    const-string v2, "Failed close record to: "

    invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    iget-object v2, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v1, v0}, Landroid/ext/la;->b(Ljava/lang/String;Ljava/lang/Throwable;)I

    goto :goto_0
.end method

.method public b()Ljava/lang/String;
    .registers 2

    .prologue
    .line 64
    iget-object v0, p0, Landroid/ext/qm;->c:Ljava/lang/String;

    return-object v0
.end method

.method public close()V
    .registers 1

    .prologue
    .line 42
    return-void
.end method

.method public flush()V
    .registers 1

    .prologue
    .line 40
    return-void
.end method

.method public write(Ljava/lang/String;)V
    .registers 3

    .prologue
    .line 47
    :try_start_0
    iget-object v0, p0, Landroid/ext/qm;->b:Ljava/io/Writer;

    invoke-virtual {v0, p1}, Ljava/io/Writer;->write(Ljava/lang/String;)V
    :try_end_0
    .catch Ljava/lang/Throwable; {:try_start_0 .. :try_end_0} :catch_0

    .line 51
    :goto_0
    return-void

    .line 48
    :catch_0
    move-exception v0

    .line 49
    invoke-direct {p0, p1, v0}, Landroid/ext/qm;->a(Ljava/lang/String;Ljava/lang/Throwable;)V

    goto :goto_0
.end method

.method public write([CII)V
    .registers 4

    .prologue
    .line 38
    return-void
.end method
