.class Lluaj/d;
.super Ljava/io/PushbackInputStream;
.source "src"


# static fields
.field static final b:I


# instance fields
.field a:Z


# direct methods
.method static constructor <clinit>()V
    .registers 1

    .prologue
    .line 373
    const-string v0, "; --[=========[ Lua assembler file generated by GameGuardian "

    invoke-virtual {v0}, Ljava/lang/String;->length()I

    move-result v0

    add-int/lit8 v0, v0, 0x4

    sput v0, Lluaj/d;->b:I

    return-void
.end method

.method private constructor <init>(Ljava/io/InputStream;)V
    .registers 3

    .prologue
    .line 375
    sget v0, Lluaj/d;->b:I

    invoke-direct {p0, p1, v0}, Ljava/io/PushbackInputStream;-><init>(Ljava/io/InputStream;I)V

    .line 372
    const/4 v0, 0x0

    iput-boolean v0, p0, Lluaj/d;->a:Z

    .line 376
    return-void
.end method

.method static a(Ljava/io/InputStream;)Lluaj/d;
    .registers 2

    .prologue
    .line 369
    instance-of v0, p0, Lluaj/d;

    if-nez v0, :cond_0

    new-instance v0, Lluaj/d;

    invoke-direct {v0, p0}, Lluaj/d;-><init>(Ljava/io/InputStream;)V

    .line 370
    :goto_0
    check-cast v0, Lluaj/d;

    return-object v0

    :cond_0
    move-object v0, p0

    goto :goto_0
.end method


# virtual methods
.method public a(Z)Lluaj/d;
    .registers 2

    .prologue
    .line 398
    iput-boolean p1, p0, Lluaj/d;->a:Z

    .line 399
    return-object p0
.end method

.method public read()I
    .registers 5

    .prologue
    .line 379
    iget-object v0, p0, Lluaj/d;->buf:[B

    .line 380
    if-nez v0, :cond_0

    new-instance v0, Ljava/io/IOException;

    invoke-direct {v0}, Ljava/io/IOException;-><init>()V

    throw v0

    .line 381
    :cond_0
    iget v1, p0, Lluaj/d;->pos:I

    sget v2, Lluaj/d;->b:I

    if-ge v1, v2, :cond_2

    iget v1, p0, Lluaj/d;->pos:I

    add-int/lit8 v2, v1, 0x1

    iput v2, p0, Lluaj/d;->pos:I

    aget-byte v0, v0, v1

    and-int/lit16 v0, v0, 0xff

    .line 383
    :goto_0
    const/16 v1, 0xef

    if-ne v0, v1, :cond_1

    iget-boolean v1, p0, Lluaj/d;->a:Z

    if-nez v1, :cond_3

    .line 395
    :cond_1
    :goto_1
    return v0

    .line 381
    :cond_2
    iget-object v0, p0, Lluaj/d;->in:Ljava/io/InputStream;

    invoke-virtual {v0}, Ljava/io/InputStream;->read()I

    move-result v0

    goto :goto_0

    .line 384
    :cond_3
    invoke-super {p0}, Ljava/io/PushbackInputStream;->read()I

    move-result v1

    .line 385
    const/16 v2, 0xbb

    if-eq v1, v2, :cond_4

    .line 386
    invoke-virtual {p0, v1}, Lluaj/d;->unread(I)V

    goto :goto_1

    .line 389
    :cond_4
    invoke-super {p0}, Ljava/io/PushbackInputStream;->read()I

    move-result v2

    .line 390
    const/16 v3, 0xbf

    if-eq v2, v3, :cond_5

    .line 391
    invoke-virtual {p0, v2}, Lluaj/d;->unread(I)V

    .line 392
    invoke-virtual {p0, v1}, Lluaj/d;->unread(I)V

    goto :goto_1

    .line 395
    :cond_5
    invoke-virtual {p0}, Lluaj/d;->read()I

    move-result v0

    goto :goto_1
.end method
